### ISSUE TITLE
Fix broken tests when running with tf 2.0

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#1705]
There are tests that break when running under TF 2.0 for various reasons:

- [x] tensorboard/plugins/debugger/debug_graphs_helper_test.py - breaks because tf.add creates nested nodes in TF 2.0 (#2583)
- [x] tensorboard/util/encoder_test.py - Audio summary using deprecated tf.contrib.ffmpeg.encode_audio. Must find replacement. (#2557)
- [x] tensorboard/data_compat_test.py - Audio summary using deprecated tf.contrib.ffmpeg.encode_audio. Must find replacement. (#2557)
- [x] tensorboard/backend/event_processing/plugin_event_accumulator_test.py - Audio summary using deprecated tf.contrib.ffmpeg.encode_audio. Must find replacement. (#2558)
- [x] tensorboard/plugins/core/core_plugin_test.py - tf.contrib.summary.* usage
- [x] tensorboard/plugins/scalar/scalars_plugin_test.py:
    - [x] tf.placeholder usage (#2522)
    - [x] tf.contrib.summary.* usage for multiplexer tests (#2522)
    - [x] tf.contrib.summary.* usage for DB writer tests (#3539)
- [x] tensorboard/plugins/debugger/interactive_debugger_plugin_test.py (#2583)
- [x] tensorboard/plugins/debugger/session_debug_test.py server fails to come up in TFv2. (#2583)
- [x] tensorboard/plugins/beholder/beholder_test.py
- [x] tensorboard/plugins/mesh/mesh_plugin_test.py (#2560)
- [x] tensorboard/plugins/mesh/summary_test.py (#2560)
- [x] tensorboard/data_compat_test.py (#2559)

(To generate this list, change `run_v1_only` to a no-op, then run all tests in TF 2.x.)

**Comment by wchargin** [comment]
I have some fixes pending. After these pull requests are merged, the
stragglers will fall into two categories:

  - debugger-related tests:
      - `tensorboard/plugins/debugger/debug_graphs_helper_test.py`
      - `tensorboard/plugins/debugger/interactive_debugger_plugin_test.py`
      - `tensorboard/plugins/debugger/session_debug_test.py`
  - users of `tf.contrib.summary.create_db_writer`:
      - `tensorboard/plugins/core/core_plugin_test.py`
      - `tensorboard/plugins/scalar/scalars_plugin_test.py`
  - beholder:
      - `tensorboard/plugins/beholder/beholder_test.py`

@caisq: Could you look into fixing the debugger plugin tests?

@nfelt: If I understand correctly, the `create_db_writer` function is
not exposed under any public API in TF 2.x (there is no `contrib`, even
under `compat.v1`). It does exist as a private symbol:

```python
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-dev20190815'
>>> from tensorflow.python.ops import summary_ops_v2
>>> summary_ops_v2.create_db_writer
<function create_db_writer at 0x7f3cfc91aea0>
```

Are we comfortable removing DB-mode from test coverage entirely (in
which case we can delete the broken scalars plugin tests and gently
refactor the core plugin tests), or should we import that private
symbol, or would you suggest something else?

As to Beholder, it looks like Beholder accepts a `session` as user
input, while also constructing some V1-only ops of its own. If Beholder
itself is incompatible with TF 2.x, should we remove the whole plugin?

**Comment by caisq** [comment]
I can look into the debugger test failures.

**Comment by caisq** [comment]
These tests in tensorboard/plugins/debugger are TF1/2 compatible now, thanks to the just-merged PR.

- tensorboard/plugins/debugger/debug_graphs_helper_test.py 
- tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
-  tensorboard/plugins/debugger/session_debug_test.py

@stephanwlee Can you update the issue description to reflect that?

**Comment by stephanwlee** [comment]
@caisq Done!

**Comment by wchargin** [comment]
The last item, Beholder, was removed in #3881. We’re done!
